### ISSUE TITLE
Integrations with PureCloud [2017-09-01]

### ISSUE THREAD

**Issue by millebesso** [LoxysoftWFM/IntegrationsMaster#1]

**Comment by millebesso** [comment]
Chat is required so this depends on https://github.com/LoxysoftWFM/ProScheduler/issues/1

**Comment by millebesso** [comment]
This issue depends on #1

**Comment by LoxyGordon** [comment]
I'm on it! Integration will be made with Legos

**Comment by LoxyGordon** [comment]
# QUESTION!

**Does markup work?**

```
IF yes THEN
    "Success!"
ELSE
    "Trump"
